### ISSUE TITLE
Create a proper MVC file structure.

### ISSUE THREAD

**Issue by wyattbarger** [wyattbarger/stock-flocker#3]

**Comment by jdgiancola** [comment]
stock-flocker/
│
├── README.md
├── package.json
├── .gitignore
├── .env             # For environment-specific settings (e.g., DB connections)
│
├── public/          # Contains all the public assets
│   ├── images/
│   ├── stylesheets/
│   │   ├── main.css
│   ├── js/
│   │   ├── app.js
│   └── index.html
│
├── node_modules/    # Node.js modules installed via npm
│
├── app.js           # Main server file
│
├── config/
│   ├── database.js  # Configuration for database connection
│
├── models/          # Contains all the data models
│   ├── stock.js     # Model for individual stock entities
│   ├── user.js      # Model for user account management
│
├── views/           # Contains templates and pages for the front-end
│   ├── layouts/
│   │   ├── main.handlebars    # Main layout template
│   ├── partials/
│   │   ├── header.handlebars
│   │   ├── footer.handlebars
│   ├── dashboard.handlebars   # Dashboard for users
│   ├── login.handlebars
│   ├── register.handlebars
│
├── controllers/     # Contains server-side logic for routing and data processing
│   ├── stockController.js
│   ├── userController.js
│
├── routes/          # Sets up the URL routes and ties routes to controllers
│   ├── stockRoutes.js
│   ├── userRoutes.js
│
└── middleware/      # Middleware functions, e.g., authentication
    ├── auth.js
